# overrides for running tests
version: '3.7'

services:
  conformance_test:
    build: ./docker/conformance
    volumes:
      - ./tests/conformance:/build/run
      - ./test_outputs:/build/output

  integration_tests:
    image: opengisch/qgis:nightly
    command: sh -c 'xvfb-run python3 -m unittest discover'
    tty: true
    volumes:
      - ./tests/integration:/integration
    working_dir: /integration
