# overrides for local development (mounts the source, enables debug, live-reload, etc.)
# DO NOT USE ON PRODUCTION !!!

version: '3.7'

services:

  caddy:
    volumes:
      - ./src/:/usr/src/app

  django:
    build:
      target: dev
    environment:
      # live-reload, show exceptions in browser, etc.
      DJANGO_DEBUG: "true"
    volumes:
      # mounting the source code for live reloading
      - ./src/:/usr/src/app
      # mounting directory to hold unit tests outputs
      - ./unit_tests_outputs/:/unit_tests_outputs
    ports:
      # making django directly accessible for debugging
      - ${DJANGO_DEV_PORT:?}:8000
      # debugpy
      - ${DEBUGPY_PORT:?}:5678
    command: python3 -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000

  postgres:
    ports:
      - ${HOST_POSTGRES_PORT:?}:5432

  conformance_test:
    build: ./docker/conformance
    volumes:
      - ./tests/conformance:/build/run
      - ./test_outputs:/build/output
    profiles:
      - testing_conformance

  integration_tests:
    image: opengisch/qgis:nightly
    command: sh -c 'xvfb-run python3 -m unittest discover'
    tty: true
    volumes:
      - ./tests/integration:/integration
    working_dir: /integration
    profiles:
      - testing_integration
