# overrides for local developpement (mounts the source, enables debug, live-reload, etc.)
# DO NOT USE ON PRODUCTION !!!

version: '3.7'

services:

  caddy:
    volumes:
      - ./src/:/usr/src/app

  django:
    build:
      args:
        DEV: "true"
    environment:
      # live-reload, show exceptions in browser, etc.
      DJANGO_DEBUG: "true"
    volumes:
      # mounting the source code for live reloading
      - ./src/:/usr/src/app
      # mounting directory to hold unit tests outputs
      - ./unit_tests_outputs/:/unit_tests_outputs
    ports:
      # making django directly accessible for debugging
      - 8000:8000
      # debugpy
      - 5678:5678
    command: python3 -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000

  postgres:
    ports:
      - 5432:5432
