# overrides for running tests

services:

  conformance_test:
    build: ./conformance-tests
    volumes:
      - ./_test_outputs:/build/run/output
      # - .:/build/run/test-run-props.xml
    profiles:
      - testing
