# Generated by Django 5.0.6 on 2024-05-17 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_2056_10fields_local_geom',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=2056, verbose_name='Geometry'),
        ),
    ]
