# Generated by Django 6.1.1 on 2026-09-23 06:02

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryZ_2056',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=2056, verbose_name='Geometry')),
            ],
        ),
    ]
