# Generated by Django 6.1.1 on 2026-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_geometryz_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerWithOrdering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
