# Generated by Django 5.0.6 on 2024-05-24 09:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_point_2056_10fields_local_geom_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Non_Null_Field_With_Default',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_bool', models.BooleanField(default=True)),
                ('field_int', models.IntegerField(blank=True, null=True)),
                ('field_str_0', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 0')),
                ('field_str_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 1')),
                ('field_str_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 2')),
                ('field_str_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 3')),
                ('field_str_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 4')),
                ('field_str_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 5')),
                ('field_str_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 6')),
                ('field_str_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 7')),
                ('field_str_8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 8')),
                ('field_str_9', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field 9')),
                ('field_non_null_with_default', models.IntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
