# Generated by Django 6.1.1 on 2026-09-25 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_layerwithordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerWithVariousTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('delay', models.DurationField(null=True)),
            ],
        ),
    ]
