# Generated by Django 6.1.1 on 2026-09-30 06:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_layerwithvarioustypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerWithConstraints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('house', 'House'), ('shed', 'Shed')], default='house', max_length=10)),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'High')], null=True)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('code', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('^[A-Z]+$')])),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
