# Generated by Django 6.1.1 on 2026-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_layerwithconstraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerwithconstraints',
            name='address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
