# Generated by Django 6.2 on 2026-09-30 10:10

import django_oapif_tests.tests.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_layerwithconstraints_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvePolygon_2056',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('geom', django_oapif_tests.tests.models.CurvePolygonField(srid=2056, verbose_name='Geometry')),
            ],
        ),
    ]
