# Generated by Django 4.1.7 on 2023-04-06 11:47

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_edge_cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DjangoModelPermissionsModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=2154)),
            ],
        ),
    ]
