# Generated by Django 4.1.7 on 2023-03-31 12:05

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_edge_cases", "0002_highlypaginated"),
    ]

    operations = [
        migrations.CreateModel(
            name="DifferentSrid",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=2154, verbose_name="Geometry"
                    ),
                ),
            ],
        ),
    ]
