# Generated by Django 4.1.7 on 2023-04-05 14:29

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_edge_cases", "0003_differentsrid"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmptyTableGeom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="SimpleGeom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name="differentsrid",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=2056),
        ),
        migrations.AlterField(
            model_name="highlypaginated",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="variousgeom",
            name="geom",
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
