# Generated by Django 4.1.7 on 2023-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficialSignType",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("active", models.BooleanField(default=True)),
                ("value_de", models.CharField(blank=True, max_length=255, null=True)),
                ("value_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("value_it", models.CharField(blank=True, max_length=255, null=True)),
                ("value_ro", models.CharField(blank=True, max_length=255, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_it", models.TextField(blank=True, null=True)),
                ("description_ro", models.TextField(blank=True, null=True)),
                ("img_de", models.ImageField(upload_to="")),
                ("img_fr", models.ImageField(upload_to="")),
                ("img_it", models.ImageField(upload_to="")),
                ("img_ro", models.ImageField(upload_to="")),
                ("img_height", models.IntegerField(default=0)),
                ("img_width", models.IntegerField(default=0)),
                ("no_dynamic_inscription", models.IntegerField(default=0)),
                (
                    "default_inscription1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_inscription2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_inscription3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "default_inscription4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
