# Generated by Django 4.2 on 2023-04-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_vl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsigntype',
            name='img_de',
            field=models.FileField(upload_to='official_signs/de'),
        ),
        migrations.AlterField(
            model_name='officialsigntype',
            name='img_fr',
            field=models.FileField(upload_to='official_signs/fr'),
        ),
        migrations.AlterField(
            model_name='officialsigntype',
            name='img_it',
            field=models.FileField(upload_to='official_signs/it'),
        ),
        migrations.AlterField(
            model_name='officialsigntype',
            name='img_ro',
            field=models.FileField(upload_to='official_signs/ro'),
        ),
    ]
