# Generated by Django 4.2 on 2023-05-05 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_vl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialsigntype',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
        ),
    ]
