# Generated by Django 4.2 on 2023-04-18 10:08

from django.db import migrations, models

import signalo.value_lists.models


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_vl", "0002_alter_officialsigntype_img_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officialsigntype",
            name="img_de",
            field=models.FileField(
                storage=signalo.value_lists.models.SignsFileSystemStorage(
                    location="/media_volume/official_signs"
                ),
                upload_to="official_signs",
            ),
        ),
        migrations.AlterField(
            model_name="officialsigntype",
            name="img_fr",
            field=models.FileField(
                storage=signalo.value_lists.models.SignsFileSystemStorage(
                    location="/media_volume/official_signs"
                ),
                upload_to="official_signs",
            ),
        ),
        migrations.AlterField(
            model_name="officialsigntype",
            name="img_it",
            field=models.FileField(
                storage=signalo.value_lists.models.SignsFileSystemStorage(
                    location="/media_volume/official_signs"
                ),
                upload_to="official_signs",
            ),
        ),
        migrations.AlterField(
            model_name="officialsigntype",
            name="img_ro",
            field=models.FileField(
                storage=signalo.value_lists.models.SignsFileSystemStorage(
                    location="/media_volume/official_signs"
                ),
                upload_to="official_signs",
            ),
        ),
    ]
