# Generated by Django 4.2 on 2023-05-05 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_vl', '0002_officialsigntype_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsigntype',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
