# Generated by Django 4.1.1 on 2022-10-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalo_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sign",
            old_name="magnitude",
            new_name="order",
        ),
    ]
