# Generated by Django 4.1.2 on 2022-10-04 16:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sign",
            name="computed_geom",
            field=django.contrib.gis.db.models.fields.PointField(
                editable=False, null=True, srid=2056, verbose_name="Geometry"
            ),
        ),
    ]
