# Generated by Django 4.1.2 on 2022-10-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signalo_app", "0002_alter_sign_computed_geom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sign",
            old_name="computed_geom",
            new_name="geom",
        ),
    ]
