# Generated by Django 4.1.8 on 2023-04-13 22:31

import uuid

import computedfields.resolver
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("signalo_vl", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Azimuth",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Pole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=2056, verbose_name="Geometry"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "_serialized",
                    models.CharField(editable=False, max_length=1000, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
        migrations.CreateModel(
            name="Sign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        editable=False, null=True, srid=2056, verbose_name="Geometry"
                    ),
                ),
                (
                    "azimuth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="azimuths",
                        related_query_name="azimuth",
                        to="signalo_core.azimuth",
                    ),
                ),
                (
                    "pole",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signs",
                        to="signalo_core.pole",
                    ),
                ),
                (
                    "sign_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="official_sign",
                        to="signalo_vl.officialsigntype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(computedfields.resolver._ComputedFieldsModelBase, models.Model),
        ),
    ]
