# Generated by Django 4.1.7 on 2023-03-30 21:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pole",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=2056, verbose_name="Geometry"
            ),
        ),
        migrations.AlterField(
            model_name="sign",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                editable=False, null=True, srid=2056, verbose_name="Geometry"
            ),
        ),
    ]
