# Generated by Django 4.2 on 2023-04-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='order',
            field=models.IntegerField(),
        ),
    ]
