# Generated by Django 4.2 on 2023-05-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='geom_after_sign_offset',
            new_name='offset',
        ),
    ]
