# Generated by Django 4.2 on 2023-05-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_core', '0002_rename_geom_after_sign_offset_sign_offset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='offset',
            new_name='offset_px',
        ),
    ]
