# Generated by Django 4.2 on 2023-04-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_core', '0002_alter_sign_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='azimuth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signs', to='signalo_core.azimuth'),
        ),
    ]
