# Generated by Django 4.1.7 on 2023-04-04 08:38

import django.contrib.gis.db.models.fields
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_core", "0002_alter_pole_geom_alter_sign_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pole",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=settings.GEOMETRY_SRID, verbose_name="Geometry"
            ),
        ),
        migrations.AlterField(
            model_name="sign",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                editable=False,
                null=True,
                srid=settings.GEOMETRY_SRID,
                verbose_name="Geometry",
            ),
        ),
    ]
