# Generated by Django 4.1.8 on 2023-04-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signalo_vl", "0001_initial"),
        ("signalo_core", "0003_alter_pole_geom_alter_sign_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="sign",
            name="sign_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="official_sign",
                to="signalo_vl.officialsigntype",
            ),
        ),
    ]
