# Generated by Django 4.2 on 2023-04-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signalo_core', '0003_alter_sign_azimuth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='azimuth',
        ),
        migrations.AddField(
            model_name='azimuth',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='azimuths', to='signalo_core.pole'),
        ),
    ]
