name: Check pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure --verbose

    - name: Pre-commit failed ! Read this
      if: failure()
      run: |
        echo 'To ensure your code is properly formatted, run: pip install pre-commit; pre-commit install;'
        echo 'Fix your current code with: pre-commit run --all-files'
