on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Set version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: python .github/workflows/_scripts/set_version_from_git.py

    - name: Build
      run: python -m build

    - name: Assert version
      env:
        GITHUB_TAG: ${{github.ref}}
      run: python scripts/assert_version_from_git.py

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
